# Generated by Django 5.0.11 on 2025-03-24 06:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_image_blogpost_image_caption_savedblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='blogger',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='blogger',
            name='social_media_links',
            field=models.TextField(blank=True, help_text='Enter social media links (one per line)'),
        ),
        migrations.AddField(
            model_name='blogger',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
