# Generated by Django 4.2.18 on 2025-03-24 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_create_missing_blogger_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogger',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='blogger',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='blogger',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='blogger',
            name='social_media_links',
        ),
        migrations.RemoveField(
            model_name='blogger',
            name='website',
        ),
    ]
